/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const LOG_OUT = 'LOG_OUT'

/// ALERTS

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'


// CATEGORY

export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR'

export const VIEW_CATEGORIES = 'VIEW_CATEGORIES'
export const VIEW_CATEGORIES_SUCCESS = 'VIEW_CATEGORIES_SUCCESS'
export const VIEW_CATEGORIES_ERROR = 'VIEW_CATEGORIES_ERROR'

export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS'
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'



// PROVIDER

export const CREATE_PROVIDER = 'CREATE_PROVIDER'
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS'
export const CREATE_PROVIDER_ERROR = 'CREATE_PROVIDER_ERROR'

export const VIEW_PROVIDER = 'VIEW_PROVIDER'
export const VIEW_PROVIDER_SUCCESS = 'VIEW_PROVIDER_SUCCESS'
export const VIEW_PROVIDER_ERROR = 'VIEW_PROVIDER_ERROR'

export const VIEW_PROVIDERS = 'VIEW_PROVIDERS'
export const VIEW_PROVIDERS_SUCCESS = 'VIEW_PROVIDERS_SUCCESS'
export const VIEW_PROVIDERS_ERROR = 'VIEW_PROVIDERS_ERROR'

export const EDIT_PROVIDER = 'EDIT_PROVIDER'
export const EDIT_PROVIDER_SUCCESS = 'EDIT_PROVIDER_SUCCESS'
export const EDIT_PROVIDER_ERROR = 'EDIT_PROVIDER_ERROR'

export const UPDATE_PROVIDER = 'UPDATE_PROVIDER'
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS'
export const UPDATE_PROVIDER_ERROR = 'UPDATE_PROVIDER_ERROR'

export const DELETE_PROVIDER = 'DELETE_PROVIDER'
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS'
export const DELETE_PROVIDER_ERROR = 'DELETE_PROVIDER_ERROR'

export const GET_PROVIDER_PRODUCTS = 'GET_PROVIDER_PRODUCTS'
export const GET_PROVIDER_PRODUCTS_SUCCESS = 'GET_PROVIDER_PRODUCTS_SUCCESS'
export const GET_PROVIDER_PRODUCTS_ERROR = 'GET_PROVIDER_PRODUCTS_ERROR'


// PRODUCT

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const VIEW_PRODUCT = 'VIEW_PRODUCT'
export const VIEW_PRODUCT_SUCCESS = 'VIEW_PRODUCT_SUCCESS'
export const VIEW_PRODUCT_ERROR = 'VIEW_PRODUCT_ERROR'

export const VIEW_PRODUCTS = 'VIEW_PRODUCTS'
export const VIEW_PRODUCTS_SUCCESS = 'VIEW_PRODUCTS_SUCCESS'
export const VIEW_PRODUCTS_ERROR = 'VIEW_PRODUCTS_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'


// PURCHASE

export const CREATE_PURCHASE = 'CREATE_PURCHASE'
export const CREATE_PURCHASE_SUCCESS = 'CREATE_PURCHASE_SUCCESS'
export const CREATE_PURCHASE_ERROR = 'CREATE_PURCHASE_ERROR'

export const VIEW_PURCHASE = 'VIEW_PURCHASE'
export const VIEW_PURCHASE_SUCCESS = 'VIEW_PURCHASE_SUCCESS'
export const VIEW_PURCHASE_ERROR = 'VIEW_PURCHASE_ERROR'

export const VIEW_PURCHASES = 'VIEW_PURCHASES'
export const VIEW_PURCHASES_SUCCESS = 'VIEW_PURCHASES_SUCCESS'
export const VIEW_PURCHASES_ERROR = 'VIEW_PURCHASES_ERROR'

export const EDIT_PURCHASE = 'EDIT_PURCHASE'
export const EDIT_PURCHASE_SUCCESS = 'EDIT_PURCHASE_SUCCESS'
export const EDIT_PURCHASE_ERROR = 'EDIT_PURCHASE_ERROR'

export const UPDATE_PURCHASE = 'UPDATE_PURCHASE'
export const UPDATE_PURCHASE_SUCCESS = 'UPDATE_PURCHASE_SUCCESS'
export const UPDATE_PURCHASE_ERROR = 'UPDATE_PURCHASE_ERROR'

export const DELETE_PURCHASE = 'DELETE_PURCHASE'
export const DELETE_PURCHASE_SUCCESS = 'DELETE_PURCHASE_SUCCESS'
export const DELETE_PURCHASE_ERROR = 'DELETE_PURCHASE_ERROR'


export const ADD_ITEM_CART = 'ADD_ITEM_CART'
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'
export const CANCEL_ITEMS_CART = 'CANCEL_ITEMS_CART'



// PURCHASE

export const CREATE_SALE = 'CREATE_SALE'
export const CREATE_SALE_SUCCESS = 'CREATE_SALE_SUCCESS'
export const CREATE_SALE_ERROR = 'CREATE_SALE_ERROR'

export const VIEW_SALE = 'VIEW_SALE'
export const VIEW_SALE_SUCCESS = 'VIEW_SALE_SUCCESS'
export const VIEW_SALE_ERROR = 'VIEW_SALE_ERROR'

export const VIEW_SALES = 'VIEW_SALES'
export const VIEW_SALES_SUCCESS = 'VIEW_SALES_SUCCESS'
export const VIEW_SALES_ERROR = 'VIEW_SALES_ERROR'

export const EDIT_SALE = 'EDIT_SALE'
export const EDIT_SALE_SUCCESS = 'EDIT_SALE_SUCCESS'
export const EDIT_SALE_ERROR = 'EDIT_SALE_ERROR'

export const UPDATE_SALE = 'UPDATE_SALE'
export const UPDATE_SALE_SUCCESS = 'UPDATE_SALE_SUCCESS'
export const UPDATE_SALE_ERROR = 'UPDATE_SALE_ERROR'

export const DELETE_SALE = 'DELETE_SALE'
export const DELETE_SALE_SUCCESS = 'DELETE_SALE_SUCCESS'
export const DELETE_SALE_ERROR = 'DELETE_PURCHASE_ERROR'


export const ADD_ITEM_CART_SALE = 'ADD_ITEM_CART_SALE'
export const DELETE_ITEM_CART_SALE = 'DELETE_ITEM_CART_SALE'
export const CANCEL_ITEMS_CART_SALE = 'CANCEL_ITEMS_CART_SALE'