/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_USER = 'GET_USER'
export const LOG_OUT = 'LOG_OUT'

/// ALERTS

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'


// CATEGORY

export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR'

export const VIEW_CATEGORIES = 'VIEW_CATEGORIES'
export const VIEW_CATEGORIES_SUCCESS = 'VIEW_CATEGORIES_SUCCESS'
export const VIEW_CATEGORIES_ERROR = 'VIEW_CATEGORIES_ERROR'

export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS'
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'



// PROVIDER

export const CREATE_PROVIDER = 'CREATE_PROVIDER'
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS'
export const CREATE_PROVIDER_ERROR = 'CREATE_PROVIDER_ERROR'

export const VIEW_PROVIDER = 'VIEW_PROVIDER'
export const VIEW_PROVIDER_SUCCESS = 'VIEW_PROVIDER_SUCCESS'
export const VIEW_PROVIDER_ERROR = 'VIEW_PROVIDER_ERROR'

export const VIEW_PROVIDERS = 'VIEW_PROVIDERS'
export const VIEW_PROVIDERS_SUCCESS = 'VIEW_PROVIDERS_SUCCESS'
export const VIEW_PROVIDERS_ERROR = 'VIEW_PROVIDERS_ERROR'

export const EDIT_PROVIDER = 'EDIT_PROVIDER'
export const EDIT_PROVIDER_SUCCESS = 'EDIT_PROVIDER_SUCCESS'
export const EDIT_PROVIDER_ERROR = 'EDIT_PROVIDER_ERROR'

export const UPDATE_PROVIDER = 'UPDATE_PROVIDER'
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS'
export const UPDATE_PROVIDER_ERROR = 'UPDATE_PROVIDER_ERROR'

export const DELETE_PROVIDER = 'DELETE_PROVIDER'
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS'
export const DELETE_PROVIDER_ERROR = 'DELETE_PROVIDER_ERROR'
